### PR TITLE
Add language codes topic to search help

### PR DESCRIPTION
**Pull request by rmglennon**
This adds a new file about language support to the published search help on mapzen.com.

cc @dianashk @missinglink

### CODE REVIEW

**Comment by rmglennon** [comment]
preview: https://precog.mapzen.com/mapzen/documentation/5a3fe3bfc9c3784afcfce651f5a10dd883a7d782/documentation/search/language-codes/

**Comment by missinglink** [comment]
looks good! we could optionally include some information about the `geocoding` (header part) of the response JSON.

eg:

```javascript
{
  "geocoding": {
    "version": "0.2",
      ...
      "lang": {
        "name": "German",
        "iso6391": "de",
        "iso6393": "deu",
        "defaulted": false
      },
      ...
    },
...
```

we return infortmation in this block about the language which the system decided to use, this is useful for users to debug responses.

**Comment by missinglink** [comment]
note that for the query above I used `?lang=de-ch` which refers to Swiss German and the response was returned in 'High German' ie Deutsch.

**Comment by rmglennon** [comment]
thanks, @missinglink - I can add this content over in pelias-doc repository.

**Pull request merged**
