### PR TITLE
WIP: terrain tiles v2

### PR DESCRIPTION
**Pull request by nvkelso**
- Connects with https://github.com/tilezen/joerd/pull/151 and specifically is needed to add new page to Terrain Tiles TOC for HTTP Status Codes.

**Preview:**

- https://precog.mapzen.com/mapzen/documentation/nvkelso/terrain-tiles-v2/

### CODE REVIEW

**Comment by nvkelso** [comment]
It's unhappy about the Joerd branch, I'll dig up how to make it work from one of my old PRs:

```
mkdir src-terrain-tiles
# Try with --wildcards for GNU tar, but fall back to BSD tar syntax for Mac.
curl -sL https://github.com/tilezen/joerd/archive/iandees/v2-docs.zip \
	| ./extract-tarball-url.py \
	| xargs curl -sL | ( \
	    tar -zxv -C src-terrain-tiles --strip-components=2 --exclude=README.md --wildcards '*/docs/' \
	 || tar -zxv -C src-terrain-tiles --strip-components=2 --exclude=README.md '*/docs/' \
	    )
Traceback (most recent call last):
  File "./extract-tarball-url.py", line 4, in <module>
    input = json.load(sys.stdin)
  File "/home/ubuntu/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/home/ubuntu/.pyenv/versions/3.4.3/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 79: invalid start byte
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by nvkelso** [comment]
@rmglennon Alternatively to the commit we could try this branch `iandees/v2-docs`.

**Comment by rmglennon** [comment]
Woo-hoo. This is now preview-able (I simplified the curl for ease): https://precog.mapzen.com/mapzen/documentation/nvkelso/terrain-tiles-v2/documentation/terrain-tiles/http-status-codes/

**Comment by nvkelso** [comment]
Per IRL converstation today:

- close this PR (don't merge it), and create new PR that only has the table of contents changes.
- or back all other changes out of this PR, once the `latest` branch of terrain docs has the required changes.

**Comment by rmglennon** [comment]
I backed out the changes to the makefile to prepare this PR for production. The test is failing because the new file (http-status-codes.md) is not yet on the latest branch. This is expected.

After that's merged, then we can merge this and have fresh, new docs. 😄

**Pull request merged**
