### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by kkowalsky**
lots of edits that have been meaning to be done. 
- adds shiny, new circleci build shield
- adds table for where mapzen product docs live
- describes how to use Precog for testing docs
- links to the writing style guide!
- how to add redirects to a doc config

I removed the 'Rapid bootstrapping' section as I think we want to view changes on Precog now?

@rmglennon would love a glance-over

### CODE REVIEW

**Comment by rmglennon** [comment]
Thanks for the changes! This looks OK. We should figure out the relationship with the style guide. It seems reasonable to keep the actual writing style content (although it needs to be added into the table of contents) in the style guide and the build process info here. It might be getting a bit long for a readme.

One thing, I believe the section on not being able to build multiple sections at once is no longer true. I think you can build the whole help locally by running make. If I'm making a big change, I'll build locally to avoid so many precog rebuilds. You need to clear out the dist folders each time you build, otherwise it won't catch your changes and will instantly say the build is done.

**Comment by kkowalsky** [comment]
I agree. Shortening this readme and maybe making a separate set of instructions for installation or updating the docs might be worthwhile (like mapzen.js's build.md). 

That updating section needs love 💖 (and correct information!). I've tried the virtualenv build and couldn't get it to work personally, so revisiting how we describe that would be great.

**Comment by kkowalsky** [comment]
can we get some forward momentum on this?

**Comment by rmglennon** [comment]
This looks OK and I think is correct! There is more detailed content https://github.com/mapzen/styleguide/blob/master/src/site/guides/doc-instructions.md that should get integrated at some point. Probably best to make a new page for the other stuff, as this one is getting pretty long.

**Comment by rmglennon** [comment]
closing for edits done in #244 and #250.

**Pull request closed without merging**
