### PR TITLE
WIP: new overview docs

### PR DESCRIPTION
**Pull request by kkowalsky**
closes #282 and #175 

- [x] finish wireframes (@souperneon)
- [x]  goal to update formatting for '/overview' page for pricing details to be 'Get Started' (@kkowalsky)
- [x]  new words for 'Get Started' div (@kkowalsky)

- [x] redesign 'Get Started' div (@souperneon)

- [x]  add detailed content for 'Get Started' steps (@rmglennon)
- [x]  pick out FAQs for both main pricing and pricing docs, create answers (@kkowalsky/@rmglennon)

### CODE REVIEW

**Comment by kkowalsky** [comment]
@rmglennon, new copy looks great. 

Is is just me or does the H1 heading level look too big? @souperneon?

**Comment by rmglennon** [comment]
Page formatting here is same as others, but I agree...perhaps we move headings on doc to H2 or something?

**Comment by kkowalsky** [comment]
is there a way we can had another section in the navbar for the different product rate limits? Ideally expose it to H3?

**Comment by souperneon** [comment]
@rmglennon and I decided to add a new section on the docs landing page that can catch all the general Mapzen level stuff like Developer overview, Flex overview and guides. That said, the 'Get Started' div will go away from this page (for now)

**Comment by rmglennon** [comment]
Thanks, @kkowalsky, for making the homepage! Looks great!

I've been working on the overview and flex landing pages where your links will point, and mz:redirects are fun!

**Comment by rmglennon** [comment]
@kkowalsky what would you think if we made one of the items under General at /documentation be Tutorials? 

Then, I could link to that page from the developer /overview when we say, "You might want to try:
Highlight mapzen.js tutorial
Search get started
Turn-by-turn tutorial"

The simplest way to do this is to add an entry under Developer Guides for something like tutorials.md. The content is just a listing of the tutorials or get started docs we have throughout the documentation. We can do that work separately from this PR.

(see https://github.com/mapzen/documentation/issues/221)

**Comment by kkowalsky** [comment]
lets wait on adding tutorials until there's bandwidth for that

**Comment by kkowalsky** [comment]
@rmglennon changes look great!

**Comment by souperneon** [comment]
@rmglennon some more notes
- In Account settings > Sign up for a Mapzen account, let's not make agree to terms a new step. For email users they have to check a box before they can proceed. It appears as a new step for GitHub users because they auth and come back to check a box. Let's make it a new paragraph and maybe even link to the terms.

- In Account settings > Add your Mapzen Flex payment method remove " Be sure to keep your credit card information updated if it expires or you are issued a new number." We will have some method of yelling at the user when their card is close to or has expired via email, dashboard alerts, etc. These will happen by june 1 and not by this launch. I think saying "have a valid credit card" is sufficient.

- Some suggestions for the Set monthly spending limits section: 
With Mapzen Flex, you can set limits on your spending each month. This gives you the comfort of knowing that your bill will remain within the maximum amount you specify. YOu will only be charged for what you use which maybe less than the limit you set for the month.
Limits can be changed at any time but cannot be set to an amount lower than the already accrued charges for that month. If no changes are made, the monthly spending limit stays the same month over month. We will notify you by email as you approach your spending limit.
(Note: I moved this last line up from the next paragraph)

- Unfinished section in Billing information > View your usage
- Left nav order can have API limits above Support?

**Comment by burritojustice** [comment]
- in 3. Customize Billing Settings, _your bill will remain within the amount you specify_ -> perhaps `will not exceed the amount you specify`

**Comment by kkowalsky** [comment]
the effective date is a nice touch on account settings @rmglennon :ok_hand:

**Comment by rmglennon** [comment]
I think I have addressed the feedback so far. Remaining known issue is that anchor links are not working within this section...investigating.

**Pull request merged**
